version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin1234}
      POSTGRES_DB: ${DB_NAME:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - '${DB_PORT:-6519}:5432'
    restart: unless-stopped
    
volumes:
  postgres:
