version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-oasis}
      POSTGRES_DB: ${POSTGRES_DB:-db}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    restart: unless-stopped

volumes:
  postgres:
